export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';

export const ARTICLE_TOGGLE_READ = 'ARTICLE_TOGGLE_READ';
export const ARTICLE_TOGGLE_FAV = 'ARTICLE_TOGGLE_FAV';
export const ARTICLE_DELETE = 'ARTICLE_DELETE';

export const ARTICLE_ADD_INIT = 'ARTICLE_ADD_INIT';
export const ARTICLE_ADD_START = 'ARTICLE_ADD_START';
export const ARTICLE_ADD_SUCCESS = 'ARTICLE_ADD_SUCCESS';
export const ARTICLE_ADD_FAIL = 'ARTICLE_ADD_FAIL';

export const SET_ARTICLES_FILTER = 'SET_ARTICLES_FILTER';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';

export const MESSANGER_SHOW_MESSAGE = 'MESSANGER_SHOW_MESSAGE';
export const MESSANGER_HIDE_MESSAGE = 'MESSANGER_HIDE_MESSAGE';
